### PR TITLE
Added support for a navbar-toggler and a collapsible navbar

### PR DESCRIPTION
**Pull request by taylorzane**
Sorted components/index and components/compiled exports.

Currently this only works for a horizontal navbar. (95% of cases)

### CODE REVIEW

**Comment by kzima** [comment]
hey @taylorzane 

Thanks for the pull request :) 

I don't know if you have seen this [http://kzima.github.io/vuestrap-base-components/#/collapse](collapse) component, but it does exactly what you want. You can wrap a hamburger in a `<vs-collapse-toggle>` tag and trigger collapse on `<vs-collapse>` element. I like the way you used `target` prop, and it probably makes sense to use same naming convention on the `<vs-collapse-toggle>`. I am curently using events to achieve same result without using `getElementById`. It's an interesting approach though. 

Please have a play with this and let me know what you think. 

In terms of sorting, I tried to keep the related stuff together, but I guess it doesn't really matter if its sorted or not. So I am happy to merge that change pending your comment on the navbar-toggler.

**Comment by taylorzane** [comment]
Hmm, I'm surprised I didn't notice that. It's a little disconcerting that you're using the same element id for `vs-collapse` and `vs-collapse-toggle`. I suppose I could always use a single group to prevent duplicate DOM ids. Let me try this out real quick and if it works for me I'll close the PR. I'll also undo the sorting, it was more of a habitual thing instead. I didn't realize you had grouped them.

**Comment by taylorzane** [comment]
@kzima Thanks for showing me that component. It works well for me. I'll go ahead and close this PR. I may help improve that component though so that people don't have to worry about pesky duplicate element ids.

**Comment by kzima** [comment]
@taylorzane cool, I was thinking about `<vs-collapse-toggle target="someId" target-group="some-groupId">`, what do you think?

**Comment by taylorzane** [comment]
That looks a lot better. Also follows bootstrap's syntax.

Something (unrelated) that I noticed was in your example for the Carousel, you had this syntax: `<vs-carousel :interval="5000" controls="false" indicators="false">`

Which is fine, but you'd either need to handle for `controls` or `indicators` being a string, and `coerce`-ing them, or just to update the example to `<vs-carousel :interval="5000" :controls="false" :indicators="false">`. Certainly an easy fix for anyone experienced with Vue, but it may cause headaches for newbies.

I figured bringing it up here was quicker than opening a frivolous PR.

**Comment by kzima** [comment]
yeah, some of the examples might be wrong, I need to go trough them at some point and review everything...

**Comment by kzima** [comment]
I went today through sample codes and fixed them all. Also updated `vs-collapse` to use `target` and `target-group` params. 0.8.2 release is up now.

**Comment by taylorzane** [comment]
Awesome! Hopefully next time I submit a PR it won't be for another already-implemented component :wink:

**Comment by kzima** [comment]
no problem, any PRs are welcome

**Pull request closed without merging**
